### PR TITLE
Render the risk area layer beneath the feature labels

### PR DESCRIPTION
**Pull request by weltenwort**
## Summary

This configures the layer with areas used to indicate the risk colors beneath the feature labels for increased readability.

closes https://trello.com/c/Xz5lnp7T

## Background

By default, `react-map-gl` appends any layers to the end of the layer stack. This means that layers defined in the map style are rendered underneath any additional user-defined layers. In this case the user-defined layers include many filled areas, which causes the feature labels such as city and road names to be occluded by the fill color.

The layer ordering can be influenced by setting the `beforeId` property on the layer definition. This PR therefore sets the `beforeId` of the `areas-fill` layer to `road-labels`, which is the bottom-most label layer in the chosen map style.

:information_source: If a different map style is chosen at some point this might have to be adapted to the layer ids of the new style.

## Previews

**Before:**
image

**After:**
image

### CODE REVIEW

**Comment by weltenwort** [comment]
:information_source: The check failures seem to be unrelated to the specific changes, but caused by infrastructure misconfiguration.

**Comment by DanielHabenicht** [comment]
> ℹ️ The check failures seem to be unrelated to the specific changes, but caused by infrastructure misconfiguration.

Yep, secrets are not shared with PRs from forked repositories. So for the preview functionality to work the PR must come from the same repo. I will add a condition to workflow so it does not turn red on forked PRs.

**Comment by weltenwort** [comment]
@DanielHabenicht the applies to the bundle size check I tried to introduce yesterday. there seems to be a workaround, which I have a PR for in #63. Maybe that would also work for the preview action?

**Comment by DanielHabenicht** [comment]
@weltenwort seems like this is what i was searching for. I made the change here #64

**Comment by kommander** [comment]
I merged the fixes for the actions. So rebasing should fix the issues?

**Comment by DanielHabenicht** [comment]
yep or close and open this pr

**Comment by weltenwort** [comment]
I obviously messed up the workflow syntax, PR incoming :see_no_evil:

**Comment by weltenwort** [comment]
Here it is: #65 

That's the just punishment for not testing a PR. :grimacing: OTOH the workflows are not exactly easy to test. :innocent:

**Comment by kommander** [comment]
Ehehehe 😃 merged #65

**Comment by weltenwort** [comment]
The preview deployment seems to show `master` and not this PR's changes. :thinking:

**Comment by DanielHabenicht** [comment]
> The preview deployment seems to show `master` and not this PR's changes. 🤔

than i might have to do another fix as @weltenwort did to get the PR source code an not the master.

**Pull request merged**
