### PR TITLE
Initial setup of testcafe and very small first test

### PR DESCRIPTION
**Pull request by ChristophWersal**

### CODE REVIEW

**Comment by kommander** [comment]
🎉

**Comment by DanielHabenicht** [comment]
Let's add it to the workflow straight away?

**Comment by ChristophWersal** [comment]
> Let's add it to the workflow straight away?

We could do that, but it would probably only makes sense if we test the new changes. Currently, testcafe tests the deployed version of the app (test.covmap.de). For this change we need to run the app and testcafe in parallel, which needs to be setup. Feel free to add it to this branch. :)

**Comment by DanielHabenicht** [comment]
Tests should now run on every PR. Also, I consolidated the pr checks into one file in order to make use of the build steps. (so in future we can cache `yarn install` to speed up the checks.

**Comment by DanielHabenicht** [comment]
You can see it working here https://github.com/DanielHabenicht/CovMapper/pull/7
Checks are done in under 2 minutes!

**Review by DanielHabenicht — APPROVED** [review]

**Pull request merged**
