### PR TITLE
chore(workflows): make sure that title follow spec

### PR DESCRIPTION
**Pull request by DanielHabenicht**

### CODE REVIEW

**Comment by kommander** [comment]
What is the spec for the title?

**Comment by DanielHabenicht** [comment]
https://www.conventionalcommits.org/en/v1.0.0/

Should I add a comment with the link if the check fails?

**Comment by kommander** [comment]
> https://www.conventionalcommits.org/en/v1.0.0/
> 
> Should I add a comment with the link if the check fails?

Macht Sinn, damit man weiss was man tun soll.

**Comment by DanielHabenicht** [comment]
@kommander done

**Review by kommander — APPROVED** [review]

**Pull request merged**
